### ISSUE TITLE
Shaders problem and possibly only happens with mobiles

### ISSUE THREAD

**Issue by latterr** [MaysLastPlays-FNF-Things/FNF-PsychEngine#32]
### Describe your problem here.

For some reason "some" shaders doesn't work and all fo them have the same error massage.

In pc the massage doesn't appear and it actually works, but in mobiles that's not the case unfortunately

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didn't

**Comment by ACoolioDude** [comment]
Probably some shaders are need to be a edited on .frag file
